apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: DeployServiceTest
  title: Deploy Service Test
  description: A template to test GitSync variables
  links:
    - url: https://www.google.com
      icon: Burp
spec:
  owner: c_neel.khamar@harness.io
  type: service
  parameters:
    - title: Deploy service
      required:
        - username
        - version
      properties:
        name:
          title: Select environments
          type: array
          items:
            type: string
            enum:
              - production
              - staging
              - development
          uniqueItems: true
          ui:widget: checkboxes       
        username:
          title: Username
          type: string
        version:
          title: Version
          type: string
        apiKeySecret:  
          title: API Key Secret
          type: string
           
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/all/orgs/default/projects/Deepesh_CDE/pipelines/workflowtest/pipeline-studio?storeType=INLINE
        inputset: 
          "name": ${{ parameters.name }}
          "username": ${{ parameters.username }}
          "pipeline.stages.deploy.variables.version": ${{ parameters.version }}
          "pipeline.stages.deploy.spec.execution.steps.ShellScript_1.spec.environmentVariables.scriptVar":  ${{ parameters.username }}
        apiKeySecret: ${{ parameters.apiKeySecret }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
