apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: DeployServiceTest Newly Updated
  title: Deploy Service Test Newly Updated
  description: Template for deploying services to Devspace. Template for deploying services to Devspace. This is a dummy workflow created just for testing purpose and the validation of description link present in the description [guidelines](https://www.google.com)
  tags:
    - deploy
    - harness
    - devspace
spec:
  owner: dummy user from neel khamar from harness c_neel.khamar@harness.io
  type: service
  parameters:
    - title: Trigger deployment
      required:
        - UserId
      properties:
        environment:
          title: Environment
          type: string
          default: Devspaces
        infrastructure:
          title: Infrastructure
          type: string
          default: infra
        UserId:
          title: UserId
          type: string
          description: Enter your name alias example if your name is John Smith, then enter johns and for snapshot just snapshot
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Trigger Deployment
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/px7xd_BFRCi-pfWPYXVjvw/module/cd/orgs/default/projects/Deepesh_CDE/pipelines/Idptemplate/executions?storeType=INLINE
        inputset:
          USERID: ${{ parameters.UserId }}
          pipeline.stages.PreDep.spec.environment.environmentRef: ${{ parameters.environment }}
          pipeline.stages.PreDep.spec.environment.infrastructureDefinitions: ${{ parameters.infrastructure }}
        apiKeySecret: dummydeepesh
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
