apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-demo-service
  title: Deploy service
  description: A template to Deploy service
spec:
  owner: deepesh.kumar@harness.io
  type: service
  parameters:
    - title: Deploy service
      required:
        - username
        - version
        - api_key
      properties:
        username:
          title: Username
          type: string
        api_key:
          title: API Key
          type: string
        version:
          title: Version
          type: string
  steps:
    - id: trigger
      name: Run Deploy service
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/all/orgs/default/projects/Deepesh_CDE/pipelines/Idptemplate/pipeline-studio/?storeType=INLINE
        inputset:
          "username": ${{ parameters.username }}
          "pipeline.stages.deploy.variables.version": ${{ parameters.version }}
          "pipeline.stages.deploy.spec.execution.steps.ShellScript_1.spec.environmentVariables.scriptVar": ${{ parameters.username }}
        apikey: ${{ parameters.api_key }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
