apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: default
  name: devspace-deploy
  title: Trigger Devspace deployment for services
  description: Template for deploying services to Devspace
  tags:
    - deploy
    - harness
    - devspace
  uid: 5a02b96e-f014-4237-ba4d-93e713ae5542
  etag: ee58563f559997cfe675eef00292feced6e7f625
spec:
  owner: idp@harness.io
  type: service
  parameters:
    - title: Trigger deployment
      required:
        - UserId
      properties:
        environment:
          title: Environment
          type: string
          default: Devspaces
        infrastructure:
          title: Infrastructure
          type: string
          default: infra
        UserId:
          title: UserId
          type: string
          description:
            Enter your name alias example if your name is John Smith, then
            enter johns and for snapshot just snapshot
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Trigger Deployment
      action: trigger:harness-custom-pipeline
      input:
        url: https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/module/ci/orgs/PROD/projects/Harness/pipelines/Deploy_Services/pipeline-studio/?storeType=REMOTE&connectorRef=org.harnessplinfra&repoName=harness-pl-infra&branch=master
        inputset:
          USERID: ${{ parameters.UserId }}
          pipeline.stages.PreDep.spec.environment.environmentRef: ${{ parameters.environment }}
          pipeline.stages.PreDep.spec.environment.infrastructureDefinitions: ${{ parameters.infrastructure }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
