apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: DynamicMethod
  title: DynamicMethod Neel
  description: A template to test
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: c_neel.khamar@harness.io
  type: service
  parameters:
    - title: Fill in some steps
      properties:
        gitusername:
          title: Github username
          description: Harness Project Identifier
          type: string
        repositoryname:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Select the Name of the
            description: Enter the Name of
            allowArbitraryValues: true
            path: "proxy/github-repo-search/search/repositories"
            params:
              q: "org:United-Airlines-Org {{ parameters.searchTerm }}"
            per_page: "100"
            arraySelector: items
            valueSelector: name
            labelSelector: name
        # formdata:
        #   title: Secret
        #   description: API Secret
        #   type: string
        # jsondata:
        #   title: Json Data
        #   description: Payload
        #   type: string
        custom:
          title: GitHub Repos Multi
          type: array
          description: Pick multiple GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
        custom1:
          title: GitHub Repos Single
          type: string
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
        custom2:
          title: GitHub Repos Custom Single
          type: string
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
            allowArbitraryValues: true
        customMulti:
          title: GitHub Repos Custom Multi
          type: array
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            label: Multi Select
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
            allowArbitraryValues: true
    - title: Fill in some more steps
      properties:
        usernameRepo:
          title: GitHub Repos
          type: string
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
  steps:
    - id: trigger
      name: Writing the GitSync Variable
      action: trigger:harness-custom-pipeline
      input:
        url: https://qa.harness.io/ng/account/zEaak-FLS425IEO7OLzMUg/module/idp-admin/orgs/default/projects/idpprojectsc/pipelines/DummyPipeline/pipeline-studio/?storeType=INLINE&stageId=DummyStage&sectionId=EXECUTION
        inputset:
          "username": ${{ parameters.username }}
          "pipeline.stages.GitsyncStageTemplate.variables.greetings": ${{ parameters['pipeline.stages.GitsyncStageTemplate.variables.greetings'] }}
        apikey: ${{ parameters.token }}
        enableVariableMapping: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
