apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: accneel
  title: Provide access to Harness account
  description: Template for providing access to Harness account [guideline](https://www.google.com)
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: wiz
  tags:
    - access
    - harness
spec:
  owner: c_neel.khamar@harness.io
  type: service
  parameters:
    - title: Fill in some steps
      properties:
        repositoryname:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Select the Name of the
            description: Enter the Name of
            allowArbitraryValues: true
            path: "proxy/github-api/search/repositories"
            params:
              q: "org:harness {{ parameters.searchTerm }}"
            per_page: "100"
            arraySelector: items
            valueSelector: name
            labelSelector: name
        gitusername:
          title: Github username
          description: Harness Project Identifier
          type: string
          default: test
        customone:
          title: GitHub Repos
          type: string
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
            allowArbitraryValues: true
        customTwo:
          title: GitHub Repos
          type: string
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
            labelSelector: id
            allowArbitraryValues: true
        customMulti:
          title: GitHub Repos Multi
          type: array
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            label: Multi Select
            allowArbitraryValues: true
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: full_name
            labelSelector: id
            minItems: 1
            maxItems: 2
        customMultiLable:
          title: GitHub Repos Multi
          type: array
          description: Pick one of GitHub Repos
          ui:field: SelectFieldFromApi
          ui:options:
            label: Multi Select
            allowArbitraryValues: true
            path: proxy/github-api/users/{{parameters.gitusername}}/repos
            valueSelector: id
            labelSelector: name
        custom:
          type: string
          # Use `SelectFieldFromApi` to configure the select field for the entry.
          ui:field: SelectFieldFromApi
          ui:options:
            title: My Dropdown title
            description: My custom description for the component

            # The Path on the Backstage API and the parameters to fetch the data for the dropdown
            path: "catalog/entity-facets"
            params:
              facet: "kind"

            # (Optional) Renders the provided text as a placeholder value into the select box.
            placeholder: "Select from options"

            # This selects the array element from the API fetch response. It finds the array with the name kind
            # under the facets object
            arraySelector: "facets.kind"

            # (Optional) This selects the field in the array to use for the value of each select item. If its not specified
            # it will use the value of the item directly.
            valueSelector: "count"
            # (Optional) This selects the field in the array to use for the label of each select item.
            labelSelector: "value"
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{parameters.name}}
